import test from 'node:test'
import assert from 'node:assert/strict'
import { spawn } from 'node:child_process'
import { once } from 'node:events'

test('EJS 编辑器支持补全、取消、写回草稿和世界书保存，不执行模板', { skip: !process.env.TAVERN_BROWSER_TESTS || !process.env.DSH_ROOT }, async t => {
  const host = spawn(process.execPath, ['tests/fixtures/worldbook-editor-ui.mjs'], { stdio: ['ignore', 'pipe', 'pipe'], env: process.env })
  t.after(() => host.kill())
  const [chunk] = await once(host.stdout, 'data')
  const url = String(chunk).trim()
  const { chromium } = await import('playwright')
  const browser = await chromium.launch({ headless: true })
  t.after(() => browser.close())
  const page = await browser.newPage({ viewport: { width: 1100, height: 850 } })
  await page.goto(url)
  await page.getByText('Alice', { exact: true }).click()
  const entry = page.locator('details').filter({ has: page.locator('summary').filter({ hasText: /^Alice$/ }) }).first()
  await entry.getByRole('button', { name: 'EJS 代码编辑', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'EJS 代码编辑器' })
  const apply = dialog.getByRole('button', { name: '应用到条目' })
  await apply.waitFor()
  await page.waitForFunction(() => !document.querySelector('.dsh-ejs-editor-footer button')?.disabled)
  const editor = page.frameLocator('iframe[title="EJS 模板代码"]')
  const input = editor.getByRole('textbox', { name: 'EJS 模板代码' })
  await editor.getByRole('button', { name: '🔤 Fonts', exact: true }).click()
  await editor.locator('#ed-font-size').fill('18')
  await editor.locator('#ed-font-family').selectOption("'Courier New',monospace")
  await editor.getByRole('button', { name: '🎨 Display', exact: true }).click()
  await editor.locator('#ed-theme').selectOption('vs-dark')
  await editor.getByRole('button', { name: '⚙️ Features', exact: true }).click()
  await editor.locator('#ed-word-wrap').check()
  await editor.getByRole('button', { name: '↹ Indent', exact: true }).click()
  await editor.locator('#ed-tab-size').fill('2')
  await editor.getByRole('button', { name: '↹ Indent', exact: true }).click()

  await input.press('ControlOrMeta+A')
  await input.fill('<% getva')
  await input.press('Control+Space')
  await editor.getByRole('option').filter({ hasText: 'getvar' }).first().waitFor()
  await dialog.getByRole('button', { name: '取消', exact: true }).click()
  assert.equal(await entry.locator('textarea.large').inputValue(), 'Alice 在钟楼值班。')
  await entry.getByRole('button', { name: 'EJS 代码编辑', exact: true }).click()
  await page.waitForFunction(() => !document.querySelector('.dsh-ejs-editor-footer button')?.disabled)
  assert.equal(await editor.locator('#ed-font-size').inputValue(), '18')
  assert.equal(await editor.locator('#ed-font-family').inputValue(), "'Courier New',monospace")
  assert.equal(await editor.locator('#ed-theme').inputValue(), 'vs-dark')
  assert.equal(await editor.locator('#ed-word-wrap').isChecked(), true)
  assert.equal(await editor.locator('#ed-tab-size').inputValue(), '2')
  assert.match(await editor.locator('.view-lines').evaluate(el => getComputedStyle(el).fontFamily), /Courier New/)
  const text = '<% window.templateWasExecuted = true; %>\nAlice 的新模板'
  await page.context().grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.evaluate(text => navigator.clipboard.writeText(text), text)
  await input.press('ControlOrMeta+A'); await input.press('ControlOrMeta+V')
  assert.equal(await page.frames().find(frame => frame.parentFrame())?.evaluate(() => window.templateWasExecuted), undefined)
  await apply.click()
  await dialog.waitFor({ state: 'detached' })
  assert.equal(await entry.locator('textarea.large').inputValue(), text)
  const saved = page.waitForResponse(response => response.url().endsWith('/rpc') && response.request().postDataJSON().method === 'updateWorldBook')
  await page.getByRole('button', { name: '保存世界书', exact: true }).click()
  const record = await (await saved).json()
  assert.equal(record.view.entries.find(item => item.comment === 'Alice').content, text)
  assert.equal(record.view.entries.find(item => item.comment === '角色库开头').content, '<角色库>')
  assert.equal(await page.evaluate(() => window.templateWasExecuted), undefined)
})
