import test from 'node:test'
import assert from 'node:assert/strict'
import {mkdtemp,rm} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {createFileResourceStore} from '../tavern-plugin/lib/domain/file-resources.js'
import {createMvuConversion,cardData} from '../tavern-plugin/lib/domain/mvu-conversion.js'
import {registerMvuConversionTools} from '../tavern-plugin/lib/domain/mvu-conversion-tools.js'
import {freezeMvuAppearance} from '../tavern-plugin/lib/domain/mvu-conversion-appearance.js'
async function fixture(t){const dataRoot=await mkdtemp(join(tmpdir(),'mvu-design-'));t.after(()=>rm(dataRoot,{recursive:true,force:true}));const resources=createFileResourceStore({dataRoot});await resources.ensure();const card={name:'星际旅人',first_mes:'飞船抵达。',extensions:{}};const sourcePath=await resources.importCard({name:'星际旅人.json',text:JSON.stringify(card)},card);const conversion=createMvuConversion({resources});const inspection=await conversion.convert({action:'inspect',sourcePath});const tools=new Map();registerMvuConversionTools({tools:{register:t=>tools.set(t.name,t)},defineTool:t=>t,conversion,chatForSession:async()=>({mode:'card'})});return {resources,conversion,tool:tools.get('tavern_design_mvu_appearance'),sourcePath,sourceRevision:inspection.sourceRevision}}
const plan={initialState:{人物:{$meta:{extensible:true,template:{姓名:'',位置:''}},甲:{姓名:'甲',位置:'驾驶舱'},乙:{姓名:'乙',位置:'货舱'}}},updateRules:'人物位置随正文移动更新。',html:'<style>article{background:#142338;color:#fff;padding:12px}</style><article><h3>✦ $1</h3><details><summary>所在位置</summary>$2</details></article>',collectionPath:'/人物',bindings:[{capture:1,path:'/姓名'},{capture:2,path:'/位置'}]}
test('新设计工具保存风格面板定义，转换直接装配且原卡无改动',async t=>{const f=await fixture(t),before=await f.resources.readText(f.sourcePath);const {report}=await f.tool.execute({sourcePath:f.sourcePath,sourceRevision:f.sourceRevision,...plan},{});const result=await f.conversion.convert({action:'apply',sourcePath:f.sourcePath,sourceRevision:f.sourceRevision,definitionRevision:report.definitionRevision,cleanup:[]});assert.equal(result.validation.valid,true,JSON.stringify(result.validation));const data=cardData(await f.resources.readCard(result.path));assert.equal(data.extensions.dsh_mvu_conversion.frozenAppearance.generated,true);assert.match(data.extensions.regex_scripts[0].replaceString,/#142338/);assert.equal(await f.resources.readText(f.sourcePath),before)})
test('美化少字段时不能保存定义',async t=>{const f=await fixture(t);await assert.rejects(f.tool.execute({sourcePath:f.sourcePath,sourceRevision:f.sourceRevision,...plan,html:'<div>$1</div>',bindings:[plan.bindings[0]]},{}),/遗漏已定义字段/)})
test('已有美化不能覆盖；生成设计不能注入脚本',()=>{assert.throws(()=>freezeMvuAppearance({extensions:{regex_scripts:[{replaceString:'<div>$1</div>'}]}},{html:'<div>$1</div>',bindings:[{capture:1,path:'/位置'}]}),/已有美化/);for(const html of ['<div>$1<script>alert(1)</script></div>','<div onclick="run()">$1</div>','<iframe></iframe><div>$1</div>'])assert.throws(()=>freezeMvuAppearance({}, {html,bindings:[{capture:1,path:'/位置'}]}))})
test('空人物集合的模板字段也不能被美化漏掉',async t=>{const f=await fixture(t);await assert.rejects(f.tool.execute({sourcePath:f.sourcePath,sourceRevision:f.sourceRevision,...plan,initialState:{人物:{$meta:plan.initialState.人物.$meta}},html:'<div>$1</div>',bindings:[plan.bindings[0]]},{}),/遗漏已定义字段/)})
